spring:
  application:
    name: saas-app
  jpa:
    hibernate:
      #create cree les tables si elles n'existent pas depuis les entities
      #on va mettre none pour empecher de creer les tables via Hibernate et le faire faire par Flyway via la script V1__Init_Common_DB.sql
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        multi_tenancy: SCHEMA #pour le multi tenant
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:saas-app-db}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    #driver-class-name: org.postgresql.Driver -- lu dans le pom.xml
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  #flyway configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:/db/migration/common
      #- classpath:/db/migration/tenant
    schemas: public
    table: flyway_schema_history
    validate-on-migrate: true

#server configuration
server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    private_key_path: ${JWT_PRIVATE_KEY_PATH:/certs/private.pem}
    public_key_path: ${JWT_PUBLIC_KEY_PATH:/certs/public.pem}
    access-token-expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: true
